### ISSUE TITLE
only one NNUE file = 10 Mb ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#12]
hi,

regarding Marvin 5.1.0 NNUE : you write the feature "New NNUE net, net-ca6610a.nnue" .. indeed i find this .nnue file after git clone but it's about 10 Mb, not the regular 20 Mb .. and the file res/marvin.ini contains a line EVAL_FILE=net-531cad4.nnue .. where can we get these other .nnue files ?  Can some 20 Mb .nnue files also be used ?  I find no information about this on your GitHub pages ..

**Comment by bmdanielsson** [comment]
No, the 20 MB file is not supported anymore. All 10 MB nets that I have done should still work. I don't think the 20 MB nets were supported in any of the official releases, only in one of the TCEC releases. That's why I didn't mention anything about it. In the future I plan to document when ever I change the format so that old nets no longer work.

The EVAL_FILE line in res/marvin.ini is wrong. I missed updating it before making the release. I will fix that. Thanks for pointing it out.

**Comment by bmdanielsson** [comment]
EVAL_FILE line in res/marvin.ini has been updated.
