### ISSUE TITLE
no eval shown in SCID ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#14]
i think i discovered a bug with SCID : when analysing a position with Marvin in SCID, all pv lines have eval 0.00 ?! And indeed their order seems random and strongly fluctuating .. this is with MultiPV 10 :

![Marvin_v5 1 0_allzero_scid_mpv10a](https://user-images.githubusercontent.com/1109281/126974249-a614057c-9c4d-4434-93a0-b824df54f23d.png)

another GUI is Nibbler, it does display proper eval values in the pv lines (using MPV 5) :

![Marvin_v5 1 0_allzero_Nibbler_mpv5a](https://user-images.githubusercontent.com/1109281/126974285-fd8c7f30-b304-42df-9623-b7495c70cd5c.png)

also in CuteChess the pv lines of Marvin are shown properly ..

**Comment by bmdanielsson** [comment]
When setting up the engine make sure to set "Directory" to the directory where the engine binary is located. The "Directory" is used as the current working directory for the engine which is where Marvin expects to find the NNUE file. If it doesn't find the NNUE file it will always return 0.

I have now fixed so that it will fallback to the old hand crafted evaluation if it doesn't find the NNUE net.
