### ISSUE TITLE
Hash full ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#8]
Using CuteChess i see the hash percentage of the engines which play against eachother. Many engines clear their hash before evaluating each new move, but the hash percentage of Marvin v5.0.0 (and also v4.0.1) increases up to 100% and is never cleared !?  I think this is a bug, but i can not test it - Marvin keeps playing ..

**Comment by bmdanielsson** [comment]
Clearing the hash table between moves is not a good idea since the information from the previous search is still useful. I took a quick look at the code of Stockfish and Ethereal and they don't actually clear the hash table between searches. Instead what they do is that they only count entries added to the table during the current search when they report hash usage to the GUI, but they still use the information from previous searches if it's available. So that's why it looks like they are clearing the hash table. Marvin on the other hand counts all entries, even old ones, when reporting hash usage.

I'll look into changing Marvin's behavior since it's confusing if it counts hash usage differently compared to other engines. Thank you for reporting this.

**Comment by bmdanielsson** [comment]
Fixed. Marvin now calculates hash usage the same way as Stockfish and Ethereal.
